### ISSUE TITLE
I cannot attach pictures into the popup window

### ISSUE THREAD

**Issue by Krukarius** [codeforgreenville/leaflet-google-sheets-template#2]
Hello,

Your tool is really nice.

I would like to ask or report (I am not good enough so far with JS), that I have problems with input pictures into the popup window likewise in example below:
http://jlord.us/sheetsee.js/demos/demo-map.html

So regarding to your code I tried:

        var popuphtml = "<em>Entrance</em> " + "<strong>" + feature.properties.PlaceName + "</strong><li><a href='"+ feature.properties.PhotoUrl + "' target='blank'>" + feature.properties.PhotoUrl + "</li><ul><li>Notes: " + feature.properties.Venue + "</li></ul>";
        layer.bindPopup(popuphtml);
        layer.setIcon(entranceIcon);
      }
    }

as well as sth like this:

              var popuphtml = "<em>Entrance</em> " + "<strong>" + feature.properties.PlaceName + "</strong><li><a href='{{{PhotoUrl}}}' target='blank'>" + feature.properties.PhotoUrl + "</li><ul><li>Notes: " + feature.properties.Venue + "</li></ul>";

but withoput the result.

In the place of image I see undefinied. Once I click on  the link I have an info like this:

Not Found
The requested URL /t20/undefined was not found on this server.

Apache/2.4.39 (Win64) PHP/5.6.40 Server at localhost Port 80

Is there a way to input image as a link included in Google Sheets column?

**Comment by allella** [comment]
Let's try the most basic thing first, get something working, and then add more to it.

If you'd like to show an image, and not a link to an image, then an _img src=_ tag would be used instead of  _a href=_

Try this first and if you're unable to get it to work then there's no point in trying to do more advanced things.

` var popuphtml = "<img src='https://en.wikipedia.org/static/images/project-logos/enwiki.png' />";
`

When you can get this working, then move onto making it work using an image variable that's set in geojson.php

For instance, it will be necessary to define the image variable, _feature.properties.PhotoUrl_, in the [geojson.php, around line #37](https://github.com/codeforgreenville/leaflet-google-sheets-template/blob/master/geojson.php#L37
)

```
      'properties' => array(
        'title' => $csvRow[2],
        'notes' => $csvRow[3],
        'property3' => $csvRow[4],
        'PhotoUrl' => 'https://en.wikipedia.org/static/images/project-logos/enwiki.png'
      )
```
These "properties" will be case Sensitive, so _PhotoUrl_ is not the same as _photoUrl_.

Now, try this in the index.html.

` var popuphtml = "<img src='" + feature.properties.PhotoUrl + "' />";
`

Additionally, I don't think the {{{PhotoUrl}}} idea is going to work because that is a syntax for a template file and this is a plain HTML file with no template functionality.

**Comment by Krukarius** [comment]
Works, thanks
